# Generated by Django 6.1.1 on 2026-09-29 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text='Positive for earned/bonus, negative for redeemed')),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned from Purchase'), ('REDEEMED', 'Redeemed for Discount'), ('BONUS', 'Welcome / Promotional Bonus'), ('REFUNDED', 'Refund / Order Cancelled'), ('ADJUSTMENT', 'Staff / Admin Adjustment')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='loyalty_loy_custome_6e26aa_idx'), models.Index(fields=['transaction_type'], name='loyalty_loy_transac_5c3ec4_idx')],
            },
        ),
    ]
